### ISSUE TITLE
blue/purple pseudo-gradient not amazing yet 

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-app#1124]
The purple/grey "stepped" gradient currently results in a complex blend of _perceived_ gradients, whereas we want each row to feel like a uniform color bar.  Adding more space between the contrasting colors would diminish that effect.  See e.g. the difference in the perceived color at the edges of the bars in this illustration:

![](http://www.denijsdesign.de/dd_images/i_perception/i_perception_2/1_gradient_green_bars.gif)

**Comment by gesa** [comment]
What do you think of this @davidascher?

![screen shot 2015-02-12 at 18 17 53](https://cloud.githubusercontent.com/assets/782056/6181146/81589906-b2e3-11e4-8ab1-af7a845d7104.png)


**Changes:**
```css
#templates .list-cell li {
    border-bottom: 6px solid rgb(225, 235, 241);
}
#templates .list-cell li:last-child {
    border-bottom: transparent;
}
```
